# syntax=docker/dockerfile:1

ARG RUBY_VERSION=4.0.1

FROM ghcr.io/ledermann/rails-base-builder:${RUBY_VERSION}-alpine AS builder

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN bundle exec bootsnap precompile --gemfile && \
    bundle exec bootsnap precompile app/ lib/


FROM ghcr.io/ledermann/rails-base-final:${RUBY_VERSION}-alpine

WORKDIR /app

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /app /app

ENTRYPOINT ["/app/bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
